image_config: &image_config

  # make sure to set your Octanner Quay repository username & password in CircleCI,
  # either as project-specific environment variables
  # or as resources in your organization's org-global Context

  IMAGE_NAME: node-with-ruby

  IMAGE_TAG: 10.1.3-2.5.0

  # NOTE: if you're modifying this config.yml file manually
  # rather than using the included setup script,
  # make sure you also add the values of your IMAGE_NAME & IMAGE_TAG variables
  # to the `test_image` job (line 55)

  LINUX_VERSION: UBUNTU_TRUSTY

  RUBY_VERSION_NUM: 2.5.0

  NODE_VERSION_NUM: 10.1.3

  # PYTHON_VERSION_NUM: # pick a version from https://python.org/ftp/python

  JAVA: false

  MYSQL_CLIENT: false

  POSTGRES_CLIENT: false

  DOCKERIZE: false

  BROWSERS: false

version: 2
jobs:
  build:
    machine: true
    environment:
      <<: *image_config

    steps:
      - checkout

      - run: bash scripts/generate.sh > Dockerfile

      - run: docker login -u $OCT_QUAY_USER -p $OCT_QUAY_PASSWORD quay.octanner.io

      - run: docker build -t quay.octanner.io/developer/$IMAGE_NAME:$IMAGE_TAG .

      - run: docker push quay.octanner.io/developer/$IMAGE_NAME:$IMAGE_TAG && sleep 10

      - store_artifacts:
          path: Dockerfile

workflows:
  version: 2
  dockerfile_wizard:
    jobs:
      - build:
          context: org-global
